# Generated by Django 2.2.6 on 2019-10-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_title_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='opening_post',
            field=models.TextField(default=' '),
        ),
    ]
